

services:
  app_petclinic:
    build: petclinic
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://clinica_vet:3306/petclinic?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USERNAME: root
      DB_PASSWORD: M@xemilianoxlr8
    restart: always
    depends_on:
      clinica_vet:
          condition: service_healthy
  clinica_vet:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: M@xemilianoxlr8
      MYSQL_DATABASE: petclinic
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
